### ISSUE TITLE
Problem with NavigationView

### ISSUE THREAD

**Issue by arashetm** [KazaiMazai/SwiftySegmentedPicker#2] opened 2022-03-14 08:51 UTC
Hi
Thanks for your job.
I put the `SegmentedPicker` into the `NavigationView`, and the appearance goes wrong.
    
<img width="616" alt="Screen Shot 2022-03-14 at 12 20 19 PM" src="https://user-images.githubusercontent.com/19370820/158137092-ccfab06c-86f7-4a3f-9f26-95c36c16ebbb.png">

<img width="373" alt="Screen Shot 2022-03-14 at 12 19 14 PM" src="https://user-images.githubusercontent.com/19370820/158136909-7a3e9984-1017-4588-ba01-21a5f0f5c758.png">

Can you help me to fix this?

**Comment by daisyramos317** [comment] 2022-05-18 01:36
it might be due to the width being calculated when the selection is added. I changed it to a fixed size and it seemed to resolve the issue

```swift
selection()
    .frame( width: frames[selectedIndex].width, height: frames[selectedIndex].height)

**Comment by KazaiMazai** [comment] 2022-05-20 22:47
> Hi Thanks for your job. I put the `SegmentedPicker` into the `NavigationView`, and the appearance goes wrong.
> 
> <img alt="Screen Shot 2022-03-14 at 12 20 19 PM" width="616" src="https://user-images.githubusercontent.com/19370820/158137092-ccfab06c-86f7-4a3f-9f26-95c36c16ebbb.png">
> 
> <img alt="Screen Shot 2022-03-14 at 12 19 14 PM" width="373" src="https://user-images.githubusercontent.com/19370820/158136909-7a3e9984-1017-4588-ba01-21a5f0f5c758.png">
> 
> Can you help me to fix this?

Hey @arashetm 

Sorry for long response, I've totally missed the notifications from github.

What's the expected behaviour you are trying to accomplish? The screenshot looks like the expected look from what is coded above. Am I missing something?

**Comment by KazaiMazai** [comment] 2022-05-20 22:48
> it might be due to the width being calculated when the selection is added. I changed it to a fixed size and it seemed to resolve the issue
> 
> ```swift
> selection()
>     .frame( width: frames[selectedIndex].width, height: frames[selectedIndex].height)
>                             
> ```

Yeah. by default, the width and height of the selection matches the size of the content items.

**Comment by daisyramos317** [comment] 2022-05-20 23:26
This is the issue below when the `SegmentedPicker` is wrapped in a navigation view. However if you use the screen bounds like `.frame(width: UIScreen.main.bounds.width  / CGFloat(frames.count), height: frames[selectedIndex].height)` it resolves the issue

https://user-images.githubusercontent.com/6922240/169624224-2ac8f92a-5159-4245-9573-7094f69f4b78.mp4

**Comment by KazaiMazai** [comment] 2022-05-21 17:02
@daisyramos317 SwiftUI never lets us get bored, lol.
I've almost found a workaround for the issues above

**Comment by KazaiMazai** [comment] 2022-05-21 20:33
@daisyramos317 @arashetm The issue above must have been solved by the following changes: https://github.com/KazaiMazai/SwiftySegmentedPicker/pull/3

Feel free to test in the v0.0.2 release and let me know if it's solved for you.

**Comment by daisyramos317** [comment] 2022-05-23 16:42
@KazaiMazai that worked nicely, thanks!

**Comment by KazaiMazai** [comment] 2022-05-23 17:32
> @KazaiMazai that worked nicely, thanks!

Welcome! Closing the issue then

**Comment by KazaiMazai** [comment] 2022-05-23 17:32
Fixed in https://github.com/KazaiMazai/SwiftySegmentedPicker/pull/3

**Closed as completed by KazaiMazai** 2022-05-23 17:32 UTC
Labels: bug, good first issue
